import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marafiki Calgary</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Marafiki Support Group
      </h1>
      <Hero />
      
    </div>
  )
}
